sonar.projectKey=iot-telemetry-platform
sonar.projectName=IoT Telemetry Platform
sonar.projectVersion=1.0.0

# Java modules
sonar.modules=spring-event-iot-platform,iot-ml-platform,frontend

# Java sources
sonar.sources=spring-event-iot-platform/services,spring-event-iot-platform/common,spring-event-iot-platform/simulator
sonar.java.source=21
sonar.java.binaries=spring-event-iot-platform/**/target/classes
sonar.java.test.binaries=spring-event-iot-platform/**/target/test-classes

# Python sources
sonar.python.version=3.11

# Test reports
sonar.junit.reportPaths=spring-event-iot-platform/**/target/surefire-reports

# Exclusions
sonar.exclusions=\
  **/target/**,\
  **/*.min.js,\
  **/node_modules/**,\
  **/dist/**,\
  **/data/**,\
  **/__pycache__/**,\
  spring-event-iot-platform/**/target/generated-sources/**

sonar.coverage.exclusions=\
  **/config/**,\
  **/*Application.java,\
  **/*Dto.java,\
  **/*Request.java,\
  **/*Response.java,\
  **/*Event.java,\
  **/simulator/**,\
  **/migrations/**

# Encoding
sonar.sourceEncoding=UTF-8
